from __future__ import annotations

import hashlib
import json
from dataclasses import asdict
from datetime import datetime, timezone
from pathlib import Path
from random import Random
from typing import Any

from .models import AssetRecord, RunArtifacts, SceneSpec, SimSpec


class LLMPlanner:
    """Parses intent into scene and simulation specs."""

    def parse(self, prompt_payload: dict[str, Any]) -> tuple[SceneSpec, SimSpec]:
        environment = prompt_payload.get("environment", {})
        objects = prompt_payload.get("objects", [])
        agents = prompt_payload.get("agents", [])
        events = prompt_payload.get("events", [])

        payload_str = json.dumps(prompt_payload, sort_keys=True)
        seed = int(hashlib.sha256(payload_str.encode()).hexdigest()[:8], 16)

        return SceneSpec(environment=environment, objects=objects), SimSpec(
            agents=agents,
            events=events,
            seed=seed,
        )


class AssetGenerator:
    """Resolves/generates assets with deterministic local cache metadata."""

    def __init__(self, cache_dir: Path) -> None:
        self.cache_dir = cache_dir
        self.cache_dir.mkdir(parents=True, exist_ok=True)

    def materialize(self, scene_spec: SceneSpec) -> list[AssetRecord]:
        assets: list[AssetRecord] = []
        for obj in scene_spec.objects:
            obj_id = obj["id"]
            klass = obj.get("class", "unknown")
            source = obj.get("source", "asset_library")
            prompt = obj.get("prompt", klass)

            key = hashlib.md5(f"{source}:{klass}:{prompt}".encode()).hexdigest()
            asset_path = self.cache_dir / f"{key}.asset.json"

            if not asset_path.exists():
                payload = {
                    "id": obj_id,
                    "class": klass,
                    "source": source,
                    "prompt": prompt,
                    "note": "Placeholder for TRELLIS/Hunyuan output or asset retrieval",
                }
                asset_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

            assets.append(
                AssetRecord(
                    id=obj_id,
                    klass=klass,
                    source=source,
                    path=str(asset_path),
                )
            )
        return assets


class SimulationCompiler:
    """Compiles runtime-ready simulation config."""

    def compile(self, sim_spec: SimSpec, scene_spec: SceneSpec) -> dict[str, Any]:
        return {
            "seed": sim_spec.seed,
            "physics": {
                "gravity": [0, -9.81, 0],
                "objects": [
                    {
                        "id": obj["id"],
                        "body": obj.get("physics", {}).get("body", "static"),
                        "mass": obj.get("physics", {}).get("mass", 0),
                    }
                    for obj in scene_spec.objects
                ],
            },
            "agents": sim_spec.agents,
            "event_graph": sorted(sim_spec.events, key=lambda e: e.get("t", 0)),
        }


class SceneAssembler:
    """Assembles scene manifest and export placeholders."""

    def assemble(
        self,
        scene_spec: SceneSpec,
        assets: list[AssetRecord],
        output_dir: Path,
    ) -> dict[str, Any]:
        objects_by_id = {obj["id"]: obj for obj in scene_spec.objects}
        nodes: list[dict[str, Any]] = []

        for asset in assets:
            obj = objects_by_id.get(asset.id, {})
            nodes.append(
                {
                    "id": asset.id,
                    "class": asset.klass,
                    "asset_path": asset.path,
                    "transform": {
                        "position": obj.get("position", [0, 0, 0]),
                        "rotation": obj.get("rotation", [0, 0, 0]),
                    },
                    "collider": asset.collider,
                    "lod": asset.lod,
                }
            )

        usd_master = output_dir / "scene_master.usda"
        glb_export = output_dir / "scene_preview.glb.json"

        usd_master.write_text(
            "#usda 1.0\n# Placeholder USD master scene generated by MVP pipeline\n",
            encoding="utf-8",
        )
        glb_export.write_text(
            json.dumps({"note": "Placeholder GLB export manifest"}, indent=2),
            encoding="utf-8",
        )

        return {
            "environment": scene_spec.environment,
            "nodes": nodes,
            "exports": {
                "usd_master": str(usd_master),
                "glb_preview": str(glb_export),
            },
        }


class BackendRunner:
    """Dummy adapter that emulates backend trajectory generation."""

    def run(self, compiled_sim: dict[str, Any], duration_s: int = 10, hz: int = 5) -> dict[str, Any]:
        rng = Random(compiled_sim["seed"])
        frames = duration_s * hz
        trajectory = []
        for f in range(frames):
            trajectory.append(
                {
                    "frame": f,
                    "time": f / hz,
                    "agent_states": [
                        {
                            "id": agent.get("id", "agent"),
                            "progress": round(min(1.0, (f + 1) / frames + rng.random() * 0.03), 4),
                        }
                        for agent in compiled_sim.get("agents", [])
                    ],
                }
            )
        return {"frames": trajectory}


class RunStore:
    def __init__(self, root: Path) -> None:
        self.root = root
        self.root.mkdir(parents=True, exist_ok=True)

    def create(self) -> RunArtifacts:
        run_id = datetime.now(timezone.utc).strftime("run_%Y%m%dT%H%M%SZ")
        run_dir = self.root / run_id
        run_dir.mkdir(parents=True, exist_ok=False)
        return RunArtifacts(run_id=run_id, root=run_dir)

    def dump_json(self, artifacts: RunArtifacts, name: str, payload: Any) -> Path:
        target = artifacts.root / name
        target.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        artifacts.add(name, target)
        return target


def run_pipeline(prompt_payload: dict[str, Any], out_root: Path) -> RunArtifacts:
    planner = LLMPlanner()
    scene_spec, sim_spec = planner.parse(prompt_payload)

    store = RunStore(out_root)
    artifacts = store.create()

    asset_gen = AssetGenerator(cache_dir=artifacts.root / "asset_cache")
    assets = asset_gen.materialize(scene_spec)

    compiler = SimulationCompiler()
    compiled_sim = compiler.compile(sim_spec, scene_spec)

    assembler = SceneAssembler()
    scene_manifest = assembler.assemble(scene_spec, assets, artifacts.root)

    backend = BackendRunner()
    trajectory = backend.run(compiled_sim)

    completed_tasks = sum(
        1
        for frame in trajectory["frames"]
        for state in frame["agent_states"]
        if state["progress"] >= 1.0
    )
    metrics = {
        "frames": len(trajectory["frames"]),
        "agents": len(compiled_sim.get("agents", [])),
        "completed_progress_events": completed_tasks,
    }

    store.dump_json(artifacts, "scene_spec.json", asdict(scene_spec))
    store.dump_json(artifacts, "sim_spec.json", asdict(sim_spec))
    store.dump_json(artifacts, "assets_manifest.json", [asdict(a) for a in assets])
    store.dump_json(artifacts, "compiled_sim.json", compiled_sim)
    store.dump_json(artifacts, "scene_manifest.json", scene_manifest)
    store.dump_json(artifacts, "trajectory.json", trajectory)
    store.dump_json(artifacts, "metrics.json", metrics)
    store.dump_json(artifacts, "run_summary.json", artifacts.to_json())

    return artifacts
